version: "2"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ~/data/discord/mongo:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - ~/data/discord/redis:/data
    ports:
      - "6379:6379"
  # discord:
  #   build: .
  #   container_name: discord
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongo
  #     - redis
